
08-02-2018 18:25:30:894 - I: 	Loaded bot ../Reference Bots/Python/
08-02-2018 18:25:30:908 - I: 	Loaded bot ../Reference Bots/Python/
08-02-2018 18:25:30:908 - I: 	Registered player py3Bot
08-02-2018 18:25:30:908 - I: 	Registered player py3Bot
08-02-2018 18:25:30:958 - I: 		OK!
08-02-2018 18:25:46:838 - I: 	Added Command DoNothingCommand for Player py3Bot
08-02-2018 18:25:47:581 - I: 	Added Command DoNothingCommand for Player py3Bot
08-02-2018 18:25:47:584 - D: 	Beginning round processing
08-02-2018 18:25:47:589 - D: 	Processing Player Commands
08-02-2018 18:25:47:594 - E: 	Failed to process command DoNothingCommand for player py3BotGameEngine.Exceptions.InvalidCommandException: There was a problem during the placement of player's py3Bot ships (DoNothing), the round will be played over
  at GameEngine.Engine.GameRoundProcessor.ProcessPlayerCommands () [0x00217] in <e37aa81d749148eb9249f33efb08046a>:0 
